name: Javascript

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    call-javascript-workflow:
        name: Analyse Javascript Code for SwagPaymentPaypal
        uses: shopware5/docker-images-testing/.github/workflows/javascript-analysis.yml@main
        with:
            plugin-name: SwagPaymentPaypal
            legacy-plugin: true
            legacy-plugin-target: Frontend
