name: PHP

on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    call-analyse-workflow:
        name: Analyse code for SwagPaymentPaypal
        uses: shopware5/docker-images-testing/.github/workflows/php-code-analysis.yml@main
        with:
            plugin-name: SwagPaymentPaypal
            legacy-plugin: true
            legacy-plugin-target: Frontend
